# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    volumes:
      - type: bind
        source: ./entrypoints.sh
        target: /entrypoints.sh
      - type: bind
        source: ./weather/data.json
        target: /weather/data.json
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - poc-network

  mongo-express:
    container_name: "mongo-express"
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - poc-network

  gcp-storage-emulator:
    image: oittaa/gcp-storage-emulator
    container_name: "gcp-storage-emulator"
    hostname: gcp-storage-emulator
    restart: always
    ports:
      - "9023:9023"
    environment:
      - PORT=9023
    volumes:
      - gcpstoragevolume:/storage
    networks:
      - poc-network

volumes:
    gcpstoragevolume:


# NETWORKS
networks:
  poc-network:
    ipam:
      driver: default
      config:
          - subnet: 189.230.0.0/16
